version: "3.7"

services:
  db:
    image: postgres:14.4
    ports:
      - 5432:5432
    volumes:
      - prisma-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  prisma-postgres:
