version: "3.7"

services:
  web:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres?schema=public
    depends_on:
      - db
  db:
    image: postgres:14.4
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - prisma-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  prisma-postgres:
